### ISSUE TITLE
Question about your sample information

### ISSUE THREAD

**Issue by duzc-Repos** [single-cell-BGI/NHPCA#1]
Hello, 
I wonder if the detailed information about sample location (e.g. which brain lobe or brain region was the sample taken from) were provided. 
Thanks for your help!

**Comment by ZhuangZK** [comment]
The neocortex were taken from frontal lobe. For the other tissues, we sampled from individual tissue but did not note down the exact location within tissue.

**Comment by duzc-Repos** [comment]
> 
Thanks for your help!
